### ISSUE TITLE
Add Formatting standard

### ISSUE THREAD

**Issue by AdvaitDhingra** [nasa/bingocpp#51]
Many C++ Repos have a certain coding format convention (like Clang-format). Maybe this could be added to bingocpp.

**Comment by gbomarito** [comment]
Thanks for the suggestion,  are you imagining something more than the .astylerc that is already in the repo?

**Comment by AdvaitDhingra** [comment]
> Thanks for the suggestion,  are you imagining something more than the .astylerc that is already in the repo?

Ah, sorry. Didn't know that was a formatter hehe
